swagger: "2.0"
info:
  title: Stat API
  version: "0.1"
  description: An API that can provide some stat of data

paths:
  /describe/channel:
    post:
      summary: Gets channel contents
      description: Returns the whole contents in the channel
      operationId: stat_api.get_channel_info
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: formData
          name: channel_name
          required: true
          description: name of the channel to search
          type: string
      responses:
        "200":
          description: Successfully returns whole contents in the channel
        "500":
          description: NOPE

  /describe/tags-category:
    post:
      summary: Gets channel contents
      description: Returns top 10 tags in input category id
      operationId: stat_api.generate_top_10_tags_in_category
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: formData
          name: category_id
          required: true
          description: category_id to search
          type: number
      responses:
        "200":
          description: Successfully returns top 10 tags
        "500":
          description: NOPE
